// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsrdsntwhufqoiwgfqqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzcmRzbnR3aHVmcW9pd2dmcXF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5NjI1MzUsImV4cCI6MjA4NjUzODUzNX0.xRnlpYgOoh-QS4MNlacdyFYsr76C0TxbcsCP3fPO9HE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});